# Stage 1: Build the frontend
FROM node:20-slim AS builder

WORKDIR /app

# Copy package files and frontend source
COPY package.json package-lock.json ./
COPY frontend/ ./frontend/

# Install all workspace dependencies
RUN npm ci

# Create stub declarations so the frontend build does not require a live IC network.
# In production the real declarations are generated by `dfx generate backend`;
# the stub lets Vite resolve the import and bundle all UI code.
RUN mkdir -p src/declarations/backend && \
    printf 'export const backend = {};\n' > src/declarations/backend/index.js

# Build the frontend
WORKDIR /app/frontend
RUN ../node_modules/.bin/vite build

# Stage 2: Serve the built static files
FROM python:3.11-slim

WORKDIR /app

# Copy built frontend assets
COPY --from=builder /app/frontend/dist ./dist

# Expose port 8000
EXPOSE 8000

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD python3 -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/')" || exit 1

# Serve with Python's built-in HTTP server
CMD ["python3", "-m", "http.server", "8000", "--directory", "dist"]
