# Stage 1: Build the frontend
FROM node:20-slim AS builder

WORKDIR /app

# Copy package files and frontend source
COPY package.json package-lock.json ./
COPY frontend/ ./frontend/

# Install all workspace dependencies
RUN npm ci

# Create stub declarations so the frontend build does not require a live IC network.
# In production the real declarations are generated by `dfx generate backend`;
# the stub lets Vite resolve the import, bundle all UI code, and display a helpful
# error message in the chat when users try to send messages without a canister.
RUN mkdir -p src/declarations/backend && \
    printf 'export const canisterId = "";\nexport const backend = {\n  chat:            async () => { throw new Error("not configured"); },\n  createBounty:    async () => { throw new Error("not configured"); },\n  getBountyValue:  async () => [],\n  privateAction:   async () => { throw new Error("not configured"); },\n  publicLog:       async () => [],\n  fileCase:        async () => { throw new Error("not configured"); },\n  castVerdict:     async () => [],\n  enrollMember:    async () => { throw new Error("not configured"); },\n  getMember:       async () => [],\n  listMembers:     async () => [],\n  commitSkill:     async () => [],\n  endorseSkill:    async () => [],\n  listSkillCommits:async () => [],\n  publishResearch: async () => { throw new Error("not configured"); },\n  listResearch:    async () => [],\n  proposeBill:     async () => { throw new Error("not configured"); },\n  castVote:        async () => [],\n  forkBill:        async () => [],\n  listBills:       async () => [],\n};\n' > src/declarations/backend/index.js

# Build the frontend
WORKDIR /app/frontend
RUN ../node_modules/.bin/vite build

# Stage 2: Serve the built static files
FROM python:3.11-slim

WORKDIR /app

# Copy built frontend assets
COPY --from=builder /app/frontend/dist ./dist

# Expose port 8000
EXPOSE 8000

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD python3 -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/')" || exit 1

# Serve with Python's built-in HTTP server
CMD ["python3", "-m", "http.server", "8000", "--directory", "dist"]
