// Stub declarations for build testing
export const backend = {
  chat: async () => '',
  createBounty: async () => ({ message: '', bounty_id: 0n }),
  getBountyValue: async () => [],
  privateAction: async () => ({ message: '' }),
  publicLog: async () => [],
  fileCase: async () => ({ case_id: 0n, jury: [] }),
  castVerdict: async () => [],
  enrollMember: async () => ({ ok: true, message: '' }),
  getMember: async () => [],
  listMembers: async () => [],
  commitSkill: async () => [],
  endorseSkill: async () => [],
  listSkillCommits: async () => [],
  publishResearch: async () => ({ message: '', research_id: 0n }),
  listResearch: async () => [],
  proposeBill: async () => ({ message: '', bill_id: 0n }),
  castVote: async () => [],
  forkBill: async () => [],
  listBills: async () => [],
};
