// This file is a stub. The real declarations are generated by `dfx generate backend`.
// Run `dfx generate backend` or `npm run prebuild` before building.
export const backend = {
  chat: async (messages) => {
    throw new Error('Backend canister not available. Run dfx generate backend first.');
  },
};

export const canisterId = '';
export const createActor = () => backend;
